In [ ]:
import numpy as np

- ndarray 생성 np.array()

In [ ]:
list1 = [1, 2, 3]
print("list1:", list1)
print("list type:", type(list1))

array1 = np.array(list1)
print("array1 :", array1)
print("array1 type", type(array1))

- ndarray 의 형태(shape)와 차원

In [12]:
array1 = np.array([1, 2, 3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape) # 3개의 데이터를 가지고 있는 1차원 array

array2 = np.array([[1,2,3], [2,3,4]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape) # 2개의 raw와 3개의 column으로 구성된 2차원 array

array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape) # 1개의 raw와 3개의 column으로 구성된 2차원 array

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


- ndarray 데이터값 확인

In [19]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)

print(type(array1))
print(array1, array1.dtype)


<class 'list'>
<class 'numpy.ndarray'>
int64


- astype()을 통한 타입 변환

In [23]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1,2.1,3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)


[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


- ndarray에서 axis 기반의 연산함수 수행

In [31]:
array2 = np.array([[1,2,3], [2,3,4]])
print(array2.sum())
print(array2.sum(axis=0))
print(array2.sum(axis=1))


15
[3 5 7]
[6 9]


- ndarray를 편리하게 생성하기 - arange, zeros, ones

In [35]:
seq_array = np.arange(10)
print(seq_array)
print(seq_array.dtype, seq_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [45]:
zero_arr = np.zeros((3, 2), dtype='int32')
print(zero_arr)
print(zero_arr.dtype, zero_arr.shape)

one_arr = np.ones((3,2))
print(one_arr)
print(one_arr.dtype, one_arr.shape)


[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


- ndarray의 shape를 변경하는 reshape()

In [56]:
arr1 = np.arange(10)
print('arr1:\n', arr1)

arr2 = arr1.reshape(2, 5)
print('arr2\n', arr2)

arr3 = arr1.reshape(5, 2)
print('arr3\n', arr3)


arr1:
 [0 1 2 3 4 5 6 7 8 9]
arr2
 [[0 1 2 3 4]
 [5 6 7 8 9]]
arr3
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


- reshape()에 -1 인자값을 부여하여 특정 차원으로 고정된 가변적인 ndarray 형태 변환

In [63]:
arr1 = np.arange(10)
print(arr1)

#컬럼 axis 크기는 5에 고정하고 로우 axis크기를 이에 맞춰 자동으로 변환. 즉 2x5 형태로 변환
arr2 = arr1.reshape(-1, 5)
print('arr2 shape:', arr2.shape)
print('arr2:\n', arr2)

#로우 axis 크기는 5로 고정하고 컬럼 axis크기는 이에 맞춰 자동으로 변환. 즉 5x2 형태로 변환
arr3 = arr1.reshape(5, -1)
print('arr3 shape:', arr3.shape)
print('arr3:\n', arr3)


[0 1 2 3 4 5 6 7 8 9]
arr2 shape: (2, 5)
arr2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
arr3 shape: (5, 2)
arr3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [78]:
# reshape()는 (-1, 1), (-1, )와같은 형태로 주로 사용됨.
# 1차원 ndarray를 2차원으로 또는 2차원 ndarray를 1차원으로 변환 시 사용
array1 = np.arange(5)

# 1차원 ndarray를 2차원으로 변환하되, 컬럼axis크기는 반드시 1이여야 함.
array2d_1 = array1.reshape(-1, 1)
print('array2d_1 shape:', array2d_1.shape)
print('array2d_1:\n', array2d_1)

# 2차원 ndarray를 1차원으로 변환
array1d = array2d_1.reshape(-1,)
print('array1d shape:', array1d.shape)
print('array1d:\n', array1d)

array2d_1 shape: (5, 1)
array2d_1:
 [[0]
 [1]
 [2]
 [3]
 [4]]
array1d shape: (5,)
array1d:
 [0 1 2 3 4]
